# Project information
site_name: 'Kuratoren-Handbuch'
site_description: 'Virtuelle Ausstellungen der Deutschen Digitalen Bibliothek'
site_author: 'Deutsche Digitale Bibliothek, Culture to Go & Grandgeorg Websolutions'

# Copyright
copyright: 'Copyright &copy; 2017 DDB, Culture to Go, Grandgeorg Websolutions'

# Structure
pages:
    - Start: index.md
    - Überblick: ueberblick.md
    - Virtuelle Ausstellungen erstellen: virtuelle-ausstellungen-erstellen.md
    - Entwickler: entwickler.md
    # - Cheatsheet: cheatsheet.md

# Theme
theme: material
theme_dir: themes/mkdocs-material/material

# Options
extra:
  logo: 'img/logo.svg'
  palette:
    primary: 'blue grey'
    accent: 'blue grey'

extra_css:
    - css/extra.css

extra_javascript:
    - js/jquery-3.1.1.min.js
    - js/extra.js

use_directory_urls: false

# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - footnotes
  - meta
  - toc(permalink=true)
  - sane_lists
  - attr_list
  - custom_span_class
  - figureAltCaption
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
